# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Meni Sadigurschi
email:
description: >- # this means to ignore newlines until "baseurl:"
  My personal site
twitter_username: menisadi
github_username: menisadi
minimal_mistakes_skin: dark
breadcrumbs: true
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Meni Sadigurschi"
  avatar : "/assets/images/profile.jpeg"
  bio    : "Data scientist and math enthusiast"
  location: "Yeruham, IL"
  email: "meni.sadi@gmail.com"
  linkedin: 
  mastodon: "https://sigmoid.social/@menisadi"
  github: "menisadi"
  googlescholar: "https://scholar.google.com/citations?user=dmGbLNYAAAAJ&hl"

lunr:
  search_within_pages: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true  

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
